# Generated by Django 5.2.7 on 2026-04-26 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='Hand-written tagline shown on the About page category tile.', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ('order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=280, unique=True)),
                ('pub_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='posts/')),
                ('caption', models.CharField(blank=True, help_text='Caption shown under the hero image (italic, centered).', max_length=160)),
                ('excerpt', models.CharField(help_text='Dek shown under the title and used as the meta description.', max_length=280)),
                ('body', models.TextField(help_text='Markdown is supported. Pull quotes use the syntax `> [!quote]` on the line above the quoted paragraph.')),
                ('reading_time', models.PositiveIntegerField(blank=True, default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='posts.category')),
                ('tags', models.ManyToManyField(blank=True, related_name='posts', to='posts.tag')),
            ],
            options={
                'ordering': ('-pub_date',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_featured', True)), fields=('is_featured',), name='one_featured_post')],
            },
        ),
    ]
