# Generated by Django 5.2.7 on 2026-05-10 03:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_normalize_image_paths"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("tech", "Tech"),
                    ("personal", "Personal"),
                    ("leadership", "Leadership"),
                ],
                db_index=True,
                default="tech",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(
                help_text="Markdown is supported: ## subheading, **bold**, *italic*, 1. numbered lists, - bulleted lists, [link text](https://example.com), `inline code`, > blockquote. Leave a blank line between paragraphs."
            ),
        ),
    ]
