# Generated by Django 5.2.7 on 2026-04-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("footer", "Footer signup"),
                            ("post-end", "Post-end signup"),
                            ("about", "About-page signup"),
                            ("admin", "Manually added in admin"),
                        ],
                        default="footer",
                        max_length=20,
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(
                        default=False,
                        help_text="Set True when double-opt-in is added later. Currently unused.",
                    ),
                ),
                ("unsubscribed", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
